### PR TITLE
Completing the feature of having the multiple tables (html) in output window

### PR DESCRIPTION
**Pull request by N-thony**
Completes #8887
@rdstern this completes the work on having multiple tables in output window. This prevents repeating the same script (which produces multiple tables) multiple times in the output window.

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@N-thony Im very happy to see this change.  It is another step towards the version of R-Instat we are aiming for.  I note that it means 2 (or more) black rectangles, the first time it is used!

image

That's not a big problem though, because the work-around, is simply to repeat the dialog.

image

I am approving for@Patowhiz to check, and hopefully merge soon.

**Comment by rdstern** [comment]
@Patowhiz this is needed by @Vitalis95 work on the 2/3 summarise dialog.  It was done by @N-thony. Could you check and hopefuly merge this one.  Thanks

**Comment by Patowhiz** [comment]
@rdstern @N-thony, could you provide an explanation of the original issue? Understanding the context and reasoning behind the change is crucial for me, especially since the code modifications here could impact other areas. 

I recommend thorough explanations with clear steps for reproducibility related to such problems to always be standard practice. This will help in identifying other potential side effects.

Thanks.

**Comment by Patowhiz** [comment]
@N-thony, from the comment by @rdstern that you [quoted](https://github.com/IDEMSInternational/R-Instat/pull/8887#issuecomment-2069643540), I'm still puzzled as to why a dialog would generate the exact same script multiple times. This seems indicative of an issue with the dialog itself, suggesting that improvements should be made there rather than in the R link. If you could provide more context on the code generated by the dialog, I would be able to offer guidance on where refactoring might be necessary.

**Comment by Patowhiz** [comment]
@N-thony, the context is a Describe Two Variable dialog that generates two file outputs after executing its R command. While the R link has been refactored to handle a collection of file paths, the output logger hasn’t been updated accordingly. This discrepancy led to the addition of a loop in the R link to add the outputs with the same R command.

To resolve this, the output logger and its dependencies need to be refactored to manage a collection of outputs post-R command execution.

I recommend starting by assessing how lines 1015 to 1030 could be integrated into the output logger. Specifically, the `AddOutput()` subroutine of the output logger should be modified to expect a collection of outputs. This change will likely require refactoring the current parameters to support the new structure.

I hope this guidance is helpful.

Thanks.

**Review by Patowhiz — CHANGES_REQUESTED** [review]
@N-thony, this is a good start.

However, in line with the original concept, each output element should be associated with an R script and its corresponding output(s). Given that an R command can produce multiple outputs, it's necessary to refactor the output element to handle a collection of outputs instead of setting empty R command strings.

This adjustment also implies that you will need to refactor the output window to accommodate this change. Essentially, output window and it's components should be capable of linking to a single output element that contains a collection of outputs.

Before you begin the implementation, I recommend reviewing all the data structures that comprise the output system at the VB.Net level. Keep in mind that these output elements are intended to be utilised by the script window in the long run. 

I hope this information is helpful.

Thanks.

**Comment by Patowhiz** [comment]
@N-thony, I'm still waiting for responses on issue #8948. Depending on the feedback from the broader team, we can decide whether to evaluate the approach taken here or redo it based on the agreed approach.

I'll reach out to @ChrisMarsh82 and @rdstern to expedite discussions and decisions on the issue. @rdstern, if you believe that resolving this issue is more urgent than the discussions on issue #8948, feel free to overrule me on this PR, then I can merge.

**Comment by Vitalis95** [comment]
@Patowhiz ,this is needed in 2/3 var summaries, Could  you merge ?

**Comment by Patowhiz** [comment]
@Vitalis95 thanks for the reminder.

@rdstern I was hoping I would get a quick feedback on issue #8948 but there has been no response on the team tagged in the issue. Considering the necessary decision is beyond us, should we go ahead and merge? We can later look into how this can be amended once we get a decision in that issue.

@N-thony in the meantime, you could resolve the conflicts then once @rdstern tests and decides that we should merge, I will go ahead and merge. Thanks.

**Comment by rdstern** [comment]
@Patowhiz I agree to go ahead, get @N-thony to resolve conflicts and merge for now.  I think I approved before and will be happy to check again.   I like your question in #8948 but it is beyond my "pay grade".  This does seem to be a topic for you and Chris to advise on, so I suggest it could be good to add to the Thursday discussion?  I wonder if it is even directly relevant, as gt has many formats for the results?

**Review by Patowhiz — DISMISSED** [review]
@rdstern I have approved this as requested. Once you test and approve. I'll go ahead and merge.

**Review by rdstern — APPROVED** [review]
@N-thony many thanks for that quick work.  @Patowhiz done a quick test and approved again.  Beck to you for approval and merging.

**Review by Patowhiz — APPROVED** [review]

**Pull request merged**
