### PR TITLE
Added New R packages

### PR DESCRIPTION
**Pull request by derekagorhom**
@N-thony here the new packages Danny wrote about in the mattermost post. 
Please can you confirm 
thanks

### CODE REVIEW

**Comment by rdstern** [comment]
@derekagorhom you don't list the packages you have included?  Perhaps @dannyparsons or @N-thony can check.
broom_helpers is one, and is by the same author as ggstats.  And I think that needs gtsummary, which is another, where the current version needs R 4.2.

**Comment by derekagorhom** [comment]
@rdstern the first one i added were ggplot2 version `0.9.1` and also the `ggstats`
i have now added the `broom.helpers` and `gtsummary`

**Comment by rdstern** [comment]
@N-thony and @derekagorhom I guess this is now redundant?  Can it be closed?

**Comment by derekagorhom** [comment]
@N-thony , @rdstern  i am closing this PR

**Pull request closed without merging**
