### PR TITLE
Corrections to probability keyboard

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes issue #8940 
@rdstern , this PR is ready for review

### CODE REVIEW

**Comment by Fidel365** [comment]
@rdstern , I made the changes requested. Also in this PR there are design changes to improve the layout of the keys in this and other keyboards.

**Review by rdstern — COMMENTED** [review]
@Fidel365 the keyboard looks extremely neat now.  I really like that.
I'm afraid I noticed one more new small item, plus 2 others I may already have written elsewhere.
a) In pf with the parameters ticked it needs two arguments, just like qf already has.
b) In the pgamma and also qgamma we need to delete the `scale=1/rate,` parameter.

**Comment by Fidel365** [comment]
@rdstern , this is ready for rereview

**Comment by Fidel365** [comment]
We are moving to PR #8955 due to conflicts with master

**Pull request closed without merging**
