### PR TITLE
Corrections to Describe> Graphs>Barchart

### PR DESCRIPTION
**Pull request by Fidel365**
fixes issue #8726 , @rdstern spare me untill tomorrow to fix the design issue(moving the lollipop argument to the checkbox), there is a lot of controls and I need to have a deeper view then by tomorrow it will be ready, otherwise the rest of the issue is ready for review and looking forwad to upcoming tasks to this.

### CODE REVIEW

**Comment by Fidel365** [comment]
@rdstern I have an issue in my vbhence I'm not yet able to fix part (a) of the issue, which is just moving the argument for the lollipop options a bit up, I will request you to review other part of the issue and I will fix this soon, thanks

**Review by rdstern — COMMENTED** [review]
@Fidel365 I write these comments as I test.
a) I note the lollipop change is still not done.  I agreed to "spare you until tomorrow".  Are you  using the "tomorrow never comes" to literally, because that was more than a week ago?

**Comment by Fidel365** [comment]
@rdstern , could this be reviewed once more?

**Review by rdstern — CHANGES_REQUESTED** [review]
@Fidel365 great thyat you now have the back-to-back working.  But did you check carefully on the lollipop?
image

I said to omi9t the Colour option, so there was  space nicely for the size.

**Comment by Fidel365** [comment]
This is replaced by PR #8851

**Pull request closed without merging**
