### PR TITLE
Set No loaded data text correctly after auto saving

### PR DESCRIPTION
**Pull request by N-thony**
fixes partially #9088

@rdstern have a look

### CODE REVIEW

**Review by rdstern — DISMISSED** [review]
@N-thony I am not sure, and you don't say what should happen.  For me it now seems to just remain with the name of the current sheet.  There is no extra message.  I am quite happy with that, so am approving.  
@Patowhiz can you check and merge?

**Comment by rdstern** [comment]
@N-thony thanks, you have explained it perfectly.  @Patowhiz previously, after backup it said no data loaded.  That is item b in #9088.  Now it is fine, and I am happy we are at last getting these details sorted out.

**Comment by Patowhiz** [comment]
@rdstern @N-thony thanks for the explanations. 

Have you both tested this using a different language to just make sure everything shown is as expected? You both speak french, would be good to us it.

I mention this because the code changes seem to suggest it was a translation issue.

**Review by Patowhiz — CHANGES_REQUESTED** [review]
@N-thony thanks for the changes. I think all you need here is to do the following:

1. Retain changes made in line 1153.
2. Retain the deletion you have made in line 1175.
3. Revert other areas to the way they were before the new additions.

Reason being, line 1175 is the one that sets the `tstatus.Text` to "No data loaded" because it uses translations from the database. Note the "No data loaded" is set in `ucrDataView` in line 298 which already translates it, so when translations like French are on, your new addition in line 1172 will never be called.

**Comment by rdstern** [comment]
Doesn't that point also relate to my #9236 ?  Remember the autosaving is also saving the updated log file.  I wonder whether you could have time (maybe with @ChrisMarsh82 ) to only auto-save when there has been a change either the log, or the data, or both.
But having no data (if previously there was data) is to be "saved".  And it seems to do no harm.

**Comment by Patowhiz** [comment]
@N-thony, my three points above were meant to outline the translation process and your response. Point 1 refers to translating "Auto saving data," and Point 2 involves removing the form translation handled within the subroutine. I hope this clarifies things a bit more.

**Review by rdstern — APPROVED** [review]

**Pull request merged**
