### PR TITLE
Added Drop Unused Level control into the Climatic > Prepare > Summary Dialog

### LINKED ISSUE #9135: Add changed control into the Climatic > Prfepare > Summary dialog
@N-thony and @lilyclements I hope this is a simple change now?

Here is the climatic summary dialog.

image

I trust it is using the same code, for most bits, as the Prepare > Data Reshape > Summary dialog?

So please could you include the new enabled Drop Uniused Levels control?  It should also be ticked by default here?  Please report if it seems complicated?  That may mean we need to think harder first.

### PR DESCRIPTION
**Pull request by derekagorhom**
Fixes #9135 
I have implemented the Drop Unused Level control in this Dialogue
@rdstern , @lilyclements can you review this 
Thanks

### CODE REVIEW

**Comment by derekagorhom** [comment]
@lilyclements and Roger need to review this....I am sure because they on the IDEMS meeting they have not come to it yet

**Comment by rdstern** [comment]
@derekagorhom thanks for the reminder.
@lilyclements I have been testing a few options and I'm now wondering whether we need this option here.
a) With annual summaries where there are multiple stations, then we currently give the summaries for each station for just the years at that station.  I wondered whether (with the @derekagorhom changes it might give all the years for each station.  It doesn't - and I wonder whether we really need that option?
b) With monthly summaries it already gives the results for each station for each year (at that station) and for each month.

So I am inclined to leave well alone.  Should we just drop the control?

**Comment by lilyclements** [comment]
@rdstern I'll leave this one to you to decide - but I am inclined to go with your thinking!

**Comment by rdstern** [comment]
@derekagorhom apologies for the changes you have tried to make.  Can you revert, and delete that control instead.  Thanks.

**Comment by derekagorhom** [comment]
@rdstern , @lilyclements  I am closing this PR instead since that was the only change requested in Issue #9135

**Pull request closed without merging**
