### PR TITLE
New Import from Climsoft Implementation

### LINKED ISSUE #7583: New feature requests on the climsoft import dialog
As a user;

1.  I may want to import data either from observation initial or final.
2. I may also not want to import the stations metadata.
3. I may want to import just the elements or stations metadata without the observation data.

The current import dialog lacks these functionalities.
I suggest redesigning the current dialog to factor in such functionalities.

### PR DESCRIPTION
**Pull request by Patowhiz**
Fixes #7583

@rdstern @mhabimana this is ready for review.

### CODE REVIEW

**Comment by rdstern** [comment]
@Patowhiz let's check on your machine over the weekend.  I assume you also have climsoft installed?

**Comment by Patowhiz** [comment]
@mhabimana kindly test this, it compliments Climsoft [PR 733](https://github.com/climsoft/Climsoft/pull/733)

**Comment by rdstern** [comment]
@Patowhiz this looks important to test and add.  I note there are now conflicts.  

Then I hope that @mhabimana can check.  I am also happy to check as well - as we did before, namely on your machine, with me asking for you to try items.
We are giving the workshop in Malawi from 1 July.  I assume it would be good for these improvements to be implemented by then?

**Comment by Patowhiz** [comment]
@rdstern yes, I can demo this next week.

**Comment by rdstern** [comment]
@Patowhiz I note this now has conflicts.  If you resolve them, I assume we can now test them on the Climsoft installations you described.  Do any of them have data in Initial?  If not, then could you add some there?

**Comment by rdstern** [comment]
@Patowhiz can you fix the conflicts.  Then @jkmusyoka could check, using the test databases.
I note for James that there was a problem of zeros in the data for the Malawi data that I think you have now fixed.  So this could be checked at the same time.
I assume the zeros problem (i.e. misssing data in each variable bacame zero) is only in the Malawi database, so the Zambia data should be ok?

**Comment by Patowhiz** [comment]
This PR has been replaced by PR #9070 due to the conflicts.

**Pull request closed without merging**
