### PR TITLE
Improvements to general graphics dialog

### PR DESCRIPTION
**Pull request by Fidel365**
Fixexs issue #9140 and replaces Pr #9151 
@rdstern this is ready for review
@N-thony the following is the change in the database
Screenshot (12)

### CODE REVIEW

**Review by rdstern — APPROVED** [review]
@Fidel365 that still looks fine.  I am approving.
@N-thony as you say this changes frm_main.  It should be a trivial check for you to make and then hopefully merge.
@rachelkg this will merge your suggested changes in the general graphics dialog.

**Comment by rdstern** [comment]
@N-thony can this be merged?

**Comment by Fidel365** [comment]
@N-thony I see, The conflicts seems many, I'll just do this quickly in new PR

**Comment by Fidel365** [comment]
We move to Pr #9190

**Pull request closed without merging**
