### PR TITLE
Implemented Describe > Three Variable Summarise

### LINKED ISSUE #4952: Describe > Two/Three Variables > Summarise
There is a lot to improve here.

I suggest a few steps, so (at least) the dialogues are consistent.  But then I think discussion is needed with @dannyparsons and @volloholic to check on the strategy.  Once that's agreed, and I would like to write the discussion points in this issue, then I suggest it could be an interesting and important task largely for @Muthenya , with support from the others?

So an initial suggestion.  The 2 dialogues remain inconsistent and should not be.  Summarise has a single receiver first and then a multiple receiver.  Graph has the same, but the other way round.

I suggest that most people will be considering 2 specific variables when they visit this dialogue.  So could we have the same idea as in the specific graphs, namely
a) The first receiver is always a single receiver.
b) The second one is also a single receiver (by default), but with the same button as on the initial receiver for the Describe > Specific > Boxplot, etc.  So it says Single, and can be changed to Multiple, in which case it becomes a Multiple receiver.  

I don't necessarily expect @dannyparsons and @volloholic to agree, even with this, but propose that the extra button will allow the idea of the dialogue to be explained clearly.

### PR DESCRIPTION
**Pull request by derekagorhom**
fixes #4952 
I have implemented the 3-variable summarise
I have done the code for: 
CxCxC, CxCxN, CxNxC, CxNxN
all the other 4 options which start with N have been made into ANOVA [see here](https://github.com/africanmathsinitiative/R-Instat/issues/4952#issuecomment-1849019028)
@rdstern , @N-thony This PR is ready for review

### CODE REVIEW

**Comment by rdstern** [comment]
@derekagorhom well done.  You have made good progress.
Now let's start by getting some of the cosmetic parts fixed:
 Here is one look at the dialog:

image

a) The title and the comment should change to say Describe Two/Three Variables
b) The second and third variables are the wrong way round.  It currently gives the second as the third, and vv.  I don't know if this affects the functions? 
c) The group box may be made wider, (so just one line) or perhaps smaller, so the by is on the second line.  Let's try first with it smaller.
d) Try to make it so that you do get the right set of ANOVA tables, when the first (multiple) set is numeric.
e) In those ANOVA tables we will need new functions, because there will be 2 x's (second and third contols) and the multiple receiver will provide the y's.  Please discuss with @fran2or and provide a copy of the existing function, so we can help you in writing it, or them.  This can be called `data_book$anova_tables2`, and initially you could make it a copy of the anova_tables while we get the code right.

**Comment by rdstern** [comment]
@derekagorhom while on cosmetic changes, the tab order, below should imply that when the first single receiver is filled, the focus moves to the second receiver.

And I don't know why the horizontal scroll is needed so early (or at all?) in the multiple receiver
image

And I notice the format table remains at the bottom of this dialog?

It's progress though.

**Comment by derekagorhom** [comment]
@N-thony the cosmetic changes are easy to do, the only case where this might not be done this week is if i am not able to create the new anova function in time. 
I have contacted last week and i will contact him again to see the way forward

**Comment by derekagorhom** [comment]
@rdstern I think this might work for the anova table, below is the equation;

`anova(lm(field ~ size + (variety*fertgrp), survey))`

`the field` is the `3rd receiver`
 `size` is the `2nd Receiver`
`(variety*fertgrp)` will be the values in the multiple receiver

The only problem i might have would be to continue to add the` * `operator to the columns added from the multiple reciever

what do you think.

**Comment by derekagorhom** [comment]
> @rdstern I think this might work for the anova table, below is the equation;
> 
> `anova(lm(field ~ size + (variety*fertgrp), survey))`
> 
> `the field` is the `3rd receiver` `size` is the `2nd Receiver` `(variety*fertgrp)` will be the values in the `multiple receiver`
> 
> The only problem i might have would be to continue to add the`*`operator to the columns added from the multiple reciever
> 
> what do you think.

**Comment by rdstern** [comment]
@derekagorhom good try, but thye ANOVA is only when the first (multiple) receiver is numeric.  So with those variables field and size are in the multiple - they are numeric.

So with those variables you have numeric by categorical by categorical.



and the model is first lm(field ~ variety + fertgrp) or veriety * fertgrp if interaction option set.

Then the same for each variable in the multiple receiver.  So for you:
Then lm(size ~ variety + fertgrp) (or * if intereaction.

**Comment by derekagorhom** [comment]
@N-thony, if perhaps i have four variable in the multiple receiver and i have to use each of the variable to make an `lm` function here
(`size`, `field`,` yield`, `fert` are the variables in the `multiple receiver`) so in theory we should get:
lm2 <-lm(data=survey,size ~ variety * fertgrp)
lm3 <-lm(data=survey,field ~ variety * fertgrp) 
lm4 <-lm(data=survey,yield~ variety * fertgrp) 
lm5 <-lm(data=survey,fert ~ variety * fertgrp) 
where each of these functions will produce `anova` each.
how would we go about this?

**Comment by rdstern** [comment]
@derekagorhom I did discuss with @lilyclements and also with @fran2or .  I found Francis is not yet set up to be an R-Instat tester, so I suggest we do ask Lily.  But could you start by helping her (and me) in the following way.  I suggest the 3 variable ANOVA could be adapted from the 2 variable function.  So could you start by copying that function code into this pull request?

**Comment by derekagorhom** [comment]
@rdstern the code for the anova function can be found in the databook you can see it below.

```
DataSheet$set("public", "anova_tables", function(x_col_names, y_col_name, signif.stars = FALSE, sign_level = FALSE, means = FALSE) {
  if(missing(x_col_names) || missing(y_col_name)) stop("Both x_col_names and y_col_names are required")
  if(sign_level || signif.stars) message("This is no longer descriptive")
  if(sign_level) end_col = 5 else end_col = 4
  for (i in seq_along(x_col_names)) {
    mod <- lm(formula = as.formula(paste0("as.numeric(", as.name(y_col_name), ") ~ ", as.name(x_col_names[i]))), data = self$get_data_frame())
    cat("ANOVA table: ", y_col_name, " ~ ", x_col_names[i], "\n", sep = "")
    print(anova(mod)[1:end_col], signif.stars = signif.stars)
    cat("\n")
    if(means) (print(model.tables(aov(mod), type = "means")))
  }
}
)

```

**Comment by lilyclements** [comment]
If I understand correctly, we want to create a new anova function with two x's and a multiple receiver to provide the y's. This can be done really nicely with the `map` function in the `purrr` package. But first, we have to add in a new `anova` table function.

In the `data_object_R6.R` file, we add:

```
DataSheet$set("public", "anova_tables2", function(x_col_names, y_col_name, signif.stars = FALSE, sign_level = FALSE, means = FALSE) {
  if(missing(x_col_names) || missing(y_col_name)) stop("Both x_col_names and y_col_names are required")
  if(sign_level || signif.stars) message("This is no longer descriptive")
  if(sign_level) end_col = 5 else end_col = 4
  mod <- lm(formula = as.formula(paste0("as.numeric(", as.name(y_col_name), ") ~ ", as.name(x_col_names[1]), " + ", as.name(x_col_names[2]))), data = self$get_data_frame())
    cat("ANOVA table: ", y_col_name, " ~ ", x_col_names[i], "\n", sep = "")
    print(anova(mod)[1:end_col], signif.stars = signif.stars)
    cat("\n")
    if(means) (print(model.tables(aov(mod), type = "means")))
}
)
```

In the instat_object_R6.R file, we add:

```
DataBook$set("public", "anova_tables2", function(data_name, x_col_names, y_col_name, signif.stars = FALSE, sign_level = FALSE, means = FALSE) {
  self$get_data_objects(data_name)$anova_tables2(x_col_names = x_col_names, y_col_name = y_col_name, signif.stars = signif.stars, sign_level = sign_level, means = means)
} 
)
```

then we can run

```
y_col_names_list <- c("yield", "year")
purrr::map(.x = y_col_names_list, .f = ~data_book$anova_tables2(data_name="adugna.sorghum",
                                                                  x_col_names=c("gen", "loc"),
                                                                  y_col_name=.x,
                                                                  signif.stars=FALSE,
                                                                  sign_level=FALSE,
                                                                  means=FALSE))
```

This gives the results as we want them

**Comment by derekagorhom** [comment]
@lilyclements i tried your function and got this error... perhaps i am doing something wrong here
image

**Comment by lilyclements** [comment]
@derekagorhom try using two x variables. Does it work then?

**Comment by derekagorhom** [comment]
@lilyclements i tried using two x variable an got this
image

**Comment by lilyclements** [comment]
@derekagorhom thank you for that - I have found and fixed the code from my last message:

```
DataSheet$set("public", "anova_tables2", function(x_col_names, y_col_name, signif.stars = FALSE, sign_level = FALSE, means = FALSE) {
  if(missing(x_col_names) || missing(y_col_name)) stop("Both x_col_names and y_col_names are required")
  if(sign_level || signif.stars) message("This is no longer descriptive")
  if(sign_level) end_col = 5 else end_col = 4
  print("A")
  print(y_col_name)
  print(x_col_names)
  mod <- lm(formula = as.formula(paste0("as.numeric(", as.name(y_col_name), ") ~ ", as.name(x_col_names[1]), " + ", as.name(x_col_names[2]))), data = self$get_data_frame())
    cat("ANOVA table: ", y_col_name, " ~ ", x_col_names[1], " + ", x_col_names[2], "\n", sep = "")
    print(anova(mod)[1:end_col], signif.stars = signif.stars)
    cat("\n")
    if(means) (print(model.tables(aov(mod), type = "means")))
}
)
```

**Comment by derekagorhom** [comment]
@lilyclements thanks for the function, it work now.
@rdstern i still need to make some design changes, but if you want to check if the function works i have pushed it onto the PR

**Comment by lilyclements** [comment]
@derekagorhom great! I'll just clarify how I believe this function fits into the design, if that helps:

```
y_col_names_list <- c("yield", "year")
purrr::map(.x = y_col_names_list, .f = ~data_book$anova_tables2(data_name="adugna.sorghum",
                                                                  x_col_names=c("gen", "loc"),
                                                                  y_col_name=.x,
                                                                  signif.stars=FALSE,
                                                                  sign_level=FALSE,
                                                                  means=FALSE))
```

* This function runs when the multiple receiver is a numerical variable
* `y_col_names_list` - this here is our values in the multiple receiver (all numerical)
* `data_name` - this is our data frame
* `x_col_names` - in here we read in the variables in the "second variable" and "third variable" receiver. So, essentially we bind them together into `c(<variable_one>, <variable_two>)`. Is that ok? Both variables are read in as strings.
* In the "Two Variable" tab, we don't have the options for `signif.stars`, `sign_level`, or `means`. They're all default `FALSE`, so I assume we want them to remain as `FALSE` here.

**Comment by derekagorhom** [comment]
> @derekagorhom and @lilyclements that's excellent. I love the ANOVA tables. Later there will be options to be added, but now the next steps are to improve the "cosmetics" for the options that produce the ANOVA tables. a) When the first variable in the multiple receiver is numeric, it should know immediately that it is an ANOVA table. Instead it thinks it is a summary table and the dialog is a bit like a contortionist until all three receivers are completed. And it changes size at various points too. Could you now examine this code and make it efficient. You may want to work with @N-thony to ensure the code is high quality, because it is a complicated dialog. I suspect it may not always want to tell the method until all 3 receivers are completed? Could you also check the multiple receiver? It seems to have an extra horizonal scroll bar?

@N-thony can we have a meeting on this
thanks

**Comment by rdstern** [comment]
@derekagorhom and @N-thony just to be clear on what may be possible?  It is in the 3 variable setting.  So I would be happy if the only thing that changes as you add variables into the receivers is the left hand box, that gradually says say:
 `numeric by categorical by numeric, `. 

 Even there I only need the first element to be completed as something is entered.  So, numeric in the example above.  If nothing then changes until all three receivers are completed, that would be fine.  I hope that will be easy to code? 

Then, once all 3 are completed it can decide on the action and show the appropriately changed dialog.

**Comment by derekagorhom** [comment]
@rdstern i have managed to reduce the amount of times the dialogue resizes when in the 3 variable summarise, can you have a look at this again?
thanks

**Review by rdstern — COMMENTED** [review]
- @derekagorhom well done.  That's very much better.  The only item I notice on layout, is that when the 2nd receiver (first single one) is completed, the focus should move automatically to the second single receiver.  It doesn't.  (I assume that's because it was adapted from the 2 variable case, where the receiver was last.  Now it is the 3rd receiver that is last.
Then we could merge I suppose, except it needs still to present better results before we produce a version to distribute.
-

**Comment by derekagorhom** [comment]
@rdstern i have made the tab order changes, can you review them again
thanks

**Comment by derekagorhom** [comment]
@rdstern can you review this
Thanks

**Comment by rdstern** [comment]
@N-thony this dialog will be exciting - I hope.  It was being done by @derekagorhom but has some problems - not his fault, but it got pretty complicated.  One limitation was the single html output tables that has now been solved.  I have also given Derek the partner dialog of 2/3 variable graphs.  So he is a bit overloaded just now.

Do you think @Vitalis95 could takehis one over.  It is another of my (getting shorter) list that should be included in ther major upgrade.  It includes 2-way (and 3-way) frequency tables and 2-way summary tables, both of which include the multiple html options!

They also include the Format Tables button that involves @Patowhiz current work.

**Comment by Vitalis95** [comment]
@derekagorhom , you can resolve the conflicts then I will take a look at it

**Comment by Vitalis95** [comment]
Moved to PR #8939

**Pull request closed without merging**
