### PR TITLE
Alterations to the start screen

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes issue #9025 
@rdstern and @rachelkg this is ready for review

### CODE REVIEW

**Review by rdstern — COMMENTED** [review]
@Fidel365 good changes:
a) In the top group the vertical space to the Paste Data from Clipboard is smaller than the spaces between the others.  I don't mind making those vertical spaces smaller.
b) You have also got rid of the vertical scroll bar in the Recent section.  That needs to stay.  I assume we can have the vertical without the horizontal scroll bars.
c) Can you change the action on the Paste Script from Clipboard so it takes you here, rather than swapping the windows:

image
 
Ideally could you go further - maybe ask @N-thony, so that if you have a script in the clipboard, then it is pasted automatically into the script window?  Here is [an example](https://ggplot2.tidyverse.org/reference/geom_path.html) halfway down on this page:

image

**Review by rdstern — COMMENTED** [review]
@Fidel365 I am pleased you are working on this, because it would be great to include the new start-up in the forthcoming version.  I'm not sure what's changed, 

image

a) But my initial view is that the spacing between the items is different in the 3 different sections.  This is what you tidied so nicely in the calculator.  Please could you do the same here?  So the vertical spacing between the advanced items is less than those between the Help items and the new Paste at the top is closer to the others.  
I think I slightly prefer the smaller spacing throughout, but it needs to look professional and hence be consistent.
b) I still can't scroll to the bottom of the More files.

**Comment by rdstern** [comment]
@Fidel365 it would be good to finish this for the next release. The tasks:
a) The vertical spacing - you neatened the keyboards well in the calculator.  I assume this is simpler.
b) For the recent files, restore the horizontal line under that section (i.e. back to the previous situation) if it is difficult to get the `More` scrolling working without it.  There is no scrolling possible now.
c) Keep the Paste Script from Keyboard as now, i.e. with the full window for the script, and adding in the pasting if there is an R file in the clipboard.

**Comment by Fidel365** [comment]
Work on this continues on Pr #9044

**Pull request closed without merging**
