### PR TITLE
Added Select/Deselect All checkbox to the output window

### PR DESCRIPTION
**Pull request by N-thony**
Fixes partially #7979 
@rdstern I have added a checkbox to Select/Deselect All elements to the output window, have a look
image
image
image

### CODE REVIEW

**Comment by rdstern** [comment]
@N-thony I had not recognised this from the title.
a) Am I correct that you have also fixed the initial black blob.  At least I didn't get it, when I did my first visualise.  No perhaps not.  It was there for the first pivot table.
b) But I also really like the new feature, with the count of the number selected and also that clicking is also the option to deselect all.  

Would it be easy to add the shift-click to selecting multiple items?  You clicl on one box, then move down and shift-click would select all between the last one selected, and this one?

Then I would be happy to see this merged as it is.  I really like it.

**Comment by rdstern** [comment]
@N-thony I may need instruction, because it seems to be working, but I'm not sure how it is deciding what to include!
I was hoping I could click on a checkbox,  then I move down, or up, and if I shift-click, then it selects all check-boxes between the first and the shift-click one.  
So its action is identical to what happens currently in selecting multiple cells in a column of the grid?

**Comment by rdstern** [comment]
I think the shift-click works as I would expect now - not sure without more testing.  So could accept it.  I wonder whether the converse could also work, namely if I click on an item that is already selected it is noIf I then shift-click anywhere else (selected or not) then everything between is deselected.  Is that easy to implement?

**Review by rdstern — APPROVED** [review]
@N-thony it is great.  Another important item ticked off my list of things we should include in the bug release!  It is better than I thought, because I hadn't considered assing a counter!
@Patowhiz over to you to check and, I hope soon merge.

**Review by rdstern — COMMENTED** [review]
@N-thony one more change I hope, before @Patowhiz checks and merges this improvement.  I selected all and then used Delete.  It works fine, but your new checkbox remains checked and I can't now uncheck it.  It should uncheck when I use delete.  Thanks

**Review by rdstern — APPROVED** [review]
@Patowhiz over to you

**Comment by rdstern** [comment]
@Patowhiz could you check and hopefully merge?

**Review by Patowhiz — CHANGES_REQUESTED** [review]
@N-thony, could you please add comments to the newly added functions and global variables in this pull request? Although we haven't consistently done this in the past, I've found that adding comments improves readability and greatly assists with future maintenance. Thank you.

**Review by rdstern — APPROVED** [review]
@Patowhiz I like this additional functionality.  Back to you to check anf hopefully merge.

**Review by Patowhiz — APPROVED** [review]

**Pull request merged**
