### PR TITLE
Scripts and sub dialogue for gt Table

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes partially #8541 
@rdstern , this is @Fidel365 pull request, I managed to solve the merge conflicts

### CODE REVIEW

**Comment by rdstern** [comment]
@lilyclements we have - at last - got the beginnings of the table-sub-dialog to test.
a) Bits do seem to work
b) I notice the Font button only appears when you click somewhere after entering, say, a title.  I think it could be visible always?
c) I tried stub, without knowing whether my table was suitable.  The footnote appeared, but not the stub label?

image

@lilyclements can you check, and then can you suggest the next steps, or do we need to discuss first.  @Patowhiz is going to do the font part, hopefully starting next week?

**Comment by Vitalis95** [comment]
@rdstern , take a look

**Comment by Vitalis95** [comment]
@rdstern , have a look at it now

**Comment by rdstern** [comment]
@Vitalis95 I was pleased to see this is working again, and with the themes which is extensive.  @Patowhiz has now taken over the tables stuff so leave this one parked for him now.

**Comment by Patowhiz** [comment]
This has now been replaced by PR #8662

**Comment by rdstern** [comment]
@Patowhiz should this be closed?

**Comment by rdstern** [comment]
@Patowhiz should this pull request be closed?

**Comment by Patowhiz** [comment]
@Vitalis95 kindly close this PR

**Comment by rdstern** [comment]
@Vitalis95 I am closing this.  Ok?

**Pull request closed without merging**
