### PR TITLE
Added  Climatic > File > Export climatic definitions dialog

### PR DESCRIPTION
**Pull request by Vitalis95**
Still in progress.

### CODE REVIEW

**Comment by lilyclements** [comment]
@Vitalis95 if you update `epicsadata`, the issue you previously reported should be sorted. Thank you for finding and reporting that one!

We now have a new problem with exporting to the buckets. We need to authenticiate first. This is achieved using the following code:

```
epicsawrap::gcs_auth_file(" <file_authenticator_token.json> ")
```

where `file_authenticator_token.json` is the `json` file containing the token to authenticate the buckets.

@Vitalis95 @Patowhiz @ChrisMarsh82 I'm not sure the best way to go about this. Do we want to have the ability to authenticate on the main dialog, as a sub-dialog from the main dialog (where OK isn't enabled until it's filled and clicked), or as a separate dialog?

Let me know your thoughts. Thanks!

**Comment by Patowhiz** [comment]
@Vitalis95 a screenshot of the current dialog design would be helpful in answering @lilyclements question.

**Comment by Vitalis95** [comment]
@Patowhiz here is the dialog, the define button leads to sub-dialog. 

This PR  is linked to issue #8885 


image

**Comment by Patowhiz** [comment]
@lilyclements considering the amount of details already on the dialog, I think a sub-dialog would be sensible. 
For Climsoft, we  currently do authentication to the Climsoft database through a sub-dialog.

**Comment by Vitalis95** [comment]
@lilyclements , there is this new error after updating ` epicsadata`

image

**Comment by lilyclements** [comment]
@Vitalis95 thank you for finding this and being patient, once again! I've fixed the problem. Can you update your `epicsawrap` package to get the fix?

`devtools::install_github("IDEMSInternational/epicsawrap")`

**Comment by rdstern** [comment]
@Vitalis95 we (including @jkmusyoka have the script from @lilyclements .  It looks as though the dialog is almost ready.  Is that true.

**Comment by lilyclements** [comment]
@rdstern quick update - @Vitalis95 and I have a meeting tomorrow (it is a public holiday today in Kenya). The only hold-back at the moment is with opening the browser from the dialog, I think. I hope this can be fixed by the `iCallType`, and then it is simply just fixes required on the `TestOK` and it's ready!

If it can't be fixed by the `iCallType`, or even if it is, we might want to have an option to connect to google buckets through the dialog - similar to how we do it on the "Import from Climsoft" dialog, but the user just has to put in the file containing their "key/token" to connect to the buckets.

**Comment by Vitalis95** [comment]
@lilyclements , have a look at the progress so far

**Pull request closed without merging**
