### PR TITLE
Improvements to the Climsoft Export dialog 

### LINKED ISSUE #9095: Improvements to the Climsoft Export dialog
Here is the current dialog:

image

My suggested changes are as follows:  
They are minor, so I hope can be undertaken quickly by @Vitalis95, but @Patowhiz needs to check and correct the suggestions below, before Vitalis starts.

a) At the top there are our "usual" radio buttons with Daily, Hourly being the 2 options.  Hourly is disabled for now.
b) Under Station  there is another single receiver with `Station ID ` as the label.  (We are deleting the Level reciever, so maybe that can be moved and used.
c) The Date and Hour remain as now.  (At least for now.)
d) The Level receiver isn't needed.

In the code the date and hour need to be combined to produce a date-time variable in the right shape.  @Patowhiz will specify.

(In our discussion Patrick mentioned that Climsoft can perhaps also be improved, but we need - for now - to be able to work with the existing version.)

In our discussions we recognise 2 different situations - there may be a third, see below:
a) Data may start in Climsoft and may then a subset corrected and returned.  This could simply adapt the file imported from Climsoft.  It can be saved as a csv and it automatically the right shape to be imported into Climsoft.
b) Data may start elsewhere.  It will be defined as climatic (if daily).  This will then be exported via the Export dialog.
c) Other Climatic management systems will also have importing of csv data.  In the future they may use the same dialog.

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes #9095 
@rdstern @Patowhiz , have a look at it

### CODE REVIEW

**Comment by Vitalis95** [comment]
@Patowhiz , have a look this

**Comment by rdstern** [comment]
@Patowhiz please can you check this time?  Taking my role as well as yours.  Then @N-thony can be the second and merge.

**Comment by Patowhiz** [comment]
@Vitalis95 thanks for this, just a few questions and suggestions. 

What is the first receiver, station, supposed to do?
Could we have the final output arranged as station id, datetime, ...elements ?

export climsoft

**Comment by Patowhiz** [comment]
@Vitalis95 below is the script produced by the dialog. I wonder why you are formatting the date time twice, first using the `as.POSIXct `and then using `format`.

```
columns <- data_book$get_columns_from_data(data_name="test_large_import", col_names=c("rain","tmax"), force_as_data_frame=TRUE)

obsDatetime <- data_book$get_columns_from_data(data_name="test_large_import", col_names="obsDatetime")

date1 <- paste(date=obsDatetime, sprintf("%02d:00:00", hour=6))

stationid <- data_book$get_columns_from_data(data_name="test_large_import", col_names="stationid")

test_large_import__climsoft2 <- data.frame(date_time=format(as.POSIXct(date1, format="%Y-%m-%d %H:%M:%S"), "%Y-%m-%d %H:%M:%S"), station_id=stationid, columns) %>% dplyr::mutate(station="test_large_import")

data_book$import_data(data_tables=list(test_large_import__climsoft2=test_large_import__climsoft2))

rm(list=c("test_large_import__climsoft2", "date1", "obsDatetime", "stationid", "columns"))
```

**Comment by Vitalis95** [comment]
@Patowhiz , I have removed the `format` function.  Please take a look.

**Comment by Patowhiz** [comment]
@Vitalis95 what about my other questions above?

**Comment by Vitalis95** [comment]
> @Vitalis95 what about my other questions above?

Check it now

**Comment by Patowhiz** [comment]
@Vitalis95 more comments below.

Check on the file exported. The date_time has a format that is not a **SQL ISO format**. Could you make it be in the format `YYYY-MM-DD HH:mm:ss` not `YYYY-MM-DDTHH:mm:ssZ`. This could be due to the `DT` column types being exported that way by `rio`, so probably making it to character when exporting may solve the issue.

The dialog produces the script below. Look at the `sprintf` R function. Should that be changed to `sprintf(fmt = "%02d:00:00", 6))` ? Note I simply made a quick look at the function implementation [here](https://www.rdocumentation.org/packages/base/versions/3.6.2/topics/sprintf), so you may be correct. 

```
columns <- data_book$get_columns_from_data(data_name="test_large_import", col_names="obsValue", force_as_data_frame=TRUE)

stationid <- data_book$get_columns_from_data(data_name="test_large_import", col_names="stationid")
obsDatetime <- data_book$get_columns_from_data(data_name="test_large_import", col_names="obsDatetime")
date1 <- paste(date=obsDatetime, sprintf("%02d:00:00", hour=6))
test_large_import__climsoft <- data.frame(station_id=stationid, date_time=as.POSIXct(date1, format="%Y-%m-%d %H:%M:%S"), columns) %>% dplyr::mutate()
data_book$import_data(data_tables=list(test_large_import__climsoft=test_large_import__climsoft))
rio::export(x=data_book$get_data_frame(data_name="test_large_import__climsoft"), file="C:/Users/patoe/Downloads/delete_r_climate_df.csv")
rm(list=c("columns", "test_large_import__climsoft", "stationid", "date1", "obsDatetime"))
```

**Comment by Vitalis95** [comment]
@Patowhiz , I changed to `write.csv` from` rio`

**Comment by rdstern** [comment]
@Patowhiz I hope that you and @N-thony can check and then merge this one?

**Review by Patowhiz — APPROVED** [review]

**Pull request merged**
