### PR TITLE
Fixes bug in the recovery feature and version number back

### PR DESCRIPTION
**Pull request by N-thony**
@rdstern sorry for your laptop, I hope you will be able to review this by next week when you are also fully back. I may add the fix on the R-instat library here too.

### CODE REVIEW

**Comment by rdstern** [comment]
@N-thony I am now gradually getting back - so on github on Danny's laptop now.  And really looking forward to the library fix.  Once that is done, I don't think I can test it until you make a new release.  So you may want to quicly make a test version 0.7.21 (or another 0.7.20, because this wasn't sent anywhere except the workshop participants.) Then I can try it on Danny's machine!  Though using his machine for development may mean the problem goes away here, because R is updated.

**Comment by rdstern** [comment]
@N-thony I am now back, with my machine, but not sure quite what I am testing here?  Is this fixing #9118?  If so, then the option seems the same as before, i.e. giving the message that it crashed, then showing the original dialog, and not doing anything.

**Review by rdstern — APPROVED** [review]
@Patowhiz I have no idea how to test this, so am approving so it can be merged.
can you check the code and merge.
Do you think @N-thony could then quickly may a new release - tonight even - that we could try tomorrow?  We have many machines that we can use at MSD to see whether it is a fix.

**Review by Patowhiz — APPROVED** [review]

**Comment by Patowhiz** [comment]
@N-thony I have now merged this. If we can get a set up by tomorrow,  then we can test this on machines that have this issue.

**Comment by rdstern** [comment]
@N-thony we now have the new release - many thanks.  We will be testing today on machines in MSD that could not run the previous release.  I am optimistically closing this issue.

**Pull request merged**
