### PR TITLE
Adding help id's for snippets-2, and general improvements to calculator

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes partially #8889 
We now continue with the second set, I am afraid it's partially because I don't want to changes on the calculator while the functions keyboard is not yet merged to avoid conflicts to that branch. So, I will work on the calculator part once I am done with functions keyboard, else, this is ready for review.

### CODE REVIEW

**Comment by rdstern** [comment]
@Fidel365 please could you check item f) One Variable Summarise in the changes you made.  I have yet to check all the changes, but most seem to be working. 

However, Describe > One Variable > Summarise still goes to the Prepare > Check Data > Summarise place.  Could you please check that you included the help context as 410 for the Describe > One Variable > Summarise.  It happens to be the one that Beryl needs to use in her latest video.

Thanks

Roger

**Comment by Fidel365** [comment]
@rdstern, this PR is ready for review and it covers the following

**Review by rdstern — COMMENTED** [review]
@Fidel365 this is all looking good - including your clear explanations.
I omitted to give you the Structured > Circular > Define ID, wheich is 175.
I note you wanted #9002 merged first.  This is approved and I am checking with @N-thony

**Comment by Fidel365** [comment]
@rdstern , I am working on the changes on a new branch, this has conflicts and so we had to move to another branch. I will update once it's ready.

**Pull request closed without merging**
