### PR TITLE
Adding four new keys to the calculator

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes issue #8820 , @rdstern this is ready for review,Other than that,  I noticed another issue with the help button in the calculator, where some of them are cut off. I will request this to be reviewed on it's own and I would work on adjusting the help button(s) tomorrow morning in a different PR, thanks.

### CODE REVIEW

**Review by rdstern — COMMENTED** [review]
@Fidel365 that's well done.
I hoped I might just approve, because the 4 keys all seem to work fine.  But 2 small points: 
 a) There is currently no tooltip for where.max button
b) You have a small error in the where.min tooltip (which makes me wonder if you have fully understood exactly what the keys do?  (Very useful if you do.)

Then @N-thony I was really delighted that Fidel noticed the problem with the R-Help button.  @Fidel365 can you please write the issue and then I am very happy that this becomes another pull request, fixed by you.  
@N-thony I would really like the whole team to be on the lookout, in this sort of way, for improvements they can make.  Maybe you could mention this point in the next team meeting.
I notice it is similar to #8817 mentioned by Rachel.  Could you add it there, and fix those at the same time.  It was allocated to Raymond 2 weeks agao, but nothing has happened.  So I am taking that one away from him at the same time.

**Comment by Fidel365** [comment]
@rdstern , I understand now, I have committed the change and thie is ready for rereview

**Comment by rdstern** [comment]
@Fidel365 I assume the conflict is because the other pull request on the calculator has now been merged.

**Comment by Fidel365** [comment]
@rdstern that's right, I can just then work on them in a new branch coming up.

**Comment by Fidel365** [comment]
These changes are now in PR #8863

**Pull request closed without merging**
