### PR TITLE
Added the Rename Tab to Column Summaries Sub-Dialog

### LINKED ISSUE #9123: A final (?) task in the summary dialog?
The Prepare > Data Reshape > Column Summaries is one of the main dialogs in R-Instat.  There is still pending work in progress, and then this issue is (I hope) the final task - at this stage to "complete" the dialog.  The changes below are for the sub-dialog and this is one that is used by multiple main dialogs.

The pending work is as follows:
a) Tidying the two-variables tab and improving the positions tab.  This is pull request #8808 and is awaiting review
b) Implementing the drop unused levels feature.  This is pull request #8986 and is (I think) also awaiting review.

There are 2 new changes - one small and one larger.
a) In the initial dialog I always untick the NTotal checkbox when teaching.  Please could it be unchecked by default.  So just the N not missing and Sum are checked.
b) Please could there be an extra `Rename` tab.  I suggest, for speed, that either @N-thony or @Patowhiz to do the coding?  I assume it is essentially the same user control as here?

image

The default width of `Name `and `New Name` should be wider, because the default names are sometimes quite long.

### PR DESCRIPTION
**Pull request by derekagorhom**
Fixes #9123 
This Implements the part B of the issue
@N-thony Please this PR has the rename tab and is able to populate the column grid but renaming the column is the issue now

### CODE REVIEW

**Comment by derekagorhom** [comment]
@rdstern this is ready for review

**Comment by rdstern** [comment]
@derekagorhom it isn't those columns to rename.  It is the summary columns that are produced by this dialog that currently have (long) fixed names.  Those are the ones to rename.  
I was impressed that you were able to do this so quickly.  Now I understand why!

**Comment by derekagorhom** [comment]
@rdstern did you want the rename to happen while using the subdialog, if so i will probably have to ask Antoine about this since the Rename dialog shows the summary columns after the user have made the summary operations.
image
What i did was make the rename update itself to show all the datatable that are available.

**Comment by derekagorhom** [comment]
Closing this PR as #9123 is closd

**Pull request closed without merging**
