### PR TITLE
Improvement to Describe > Tables dialog

### PR DESCRIPTION
**Pull request by Vitalis95**
Fixes partly #9010 
@rdstern , @N-thony  @lilyclements 
Added  Column factors control

### CODE REVIEW

**Comment by rdstern** [comment]
@Vitalis95 it is a start - but
a) Move the significant figures and column factors controls down so ticking margins is still ok.  This dialog can be deeper - no problem, because the Summary button is much deeper.

image

b) Set the upper limit, in the up-down to be the number of factors in the receiver.
c) Include the table options button..  In the same position as in the presentation dialog below, but a bit closer to the bottom of the selector (as is the Graph Options button in all the graphs.

image

**Comment by Vitalis95** [comment]
@Patowhiz, In the Tables Option sub-dialog, the Summary Tables dialog produces gt tables and already includes `gt::gt()`. If we set the parameter with 'gt' as the name before using this sub-dialog, we end up with `gt::gt() `being called twice, which causes an error.

**Comment by Patowhiz** [comment]
@Vitalis95 I'm not sure I've understood you. The subdialog never adds gt::gt() parameter.  It expects the dialog to do so. What the subdialog does is adding other gt parameters.  

Have a look at the presentation dialog and see how the subdialog is called.

**Comment by Vitalis95** [comment]
@rdstern , have a look at it. I will change the names  in database for part `a, b & c` of the issue in separate PR

**Review by rdstern — CHANGES_REQUESTED** [review]
@Vitalis95 for the frequency tables it looks great already, and also already links to gt.  That should make is very easy for @Patowhiz .  
a) Could you make the Column factors up-down go down to 0, rather than 1.
 Here is the summary option in the dialog and it is almost working already!  Great:

image

b) Cosmetic, could you please line up the left hand side of the 3 rows, and also move the up-downs a bit to the right, so there is more space for translations.
c) The Column "Factors" up-down always goes to zero, when Ok is pressed, and so the table always has everything in rows!
d) The variables correctly went to 4, but then so did the summaries.  That should have become 5, and the 3 up-downs should then always go to 5.

**Review by rdstern — COMMENTED** [review]
@Vitalis95 that looks great.  
a) In the frequencies (and a bit in the variates, there is a lot of flashing of the dialog, when I change the up-down.  Can that be made more efficient?
b) @Patowhiz I think this pull request is now ready for you to "take over".  In the frequencies Vitalis has even done the spanner I think.  This remains to be done for the summaries.  I don't quite know where Lily's "trick" comes in, but an excited that we are perhaps on the home run here.

**Comment by Patowhiz** [comment]
@rdstern once this merged anf gives the output that you I'm happy to take over.
I'm assuming all options are working as expected and the table outputs (without the formatting) are what you expected? The idea is, the table dialogs should be able to give you the table outputs(which have hard coded column spanners) minus formatting. That's where @lilyclements code comes in. Then the formatting will be done on top of what the dialog produces once @lilyclements writes the necessary functions or writes to the gt team as Danny recommended.

**Comment by rdstern** [comment]
@Patowhiz couldn't you take over now please?  Then we have a chance that the tables could actually be working in under a year, since you started!  I think you could complete the pull request and hopefully link in your sub-dialog pretty quickly?  Then there is "just" the nanoplots!

**Comment by Vitalis95** [comment]
@rdstern , its no longer flashing now

**Comment by rdstern** [comment]
@Vitalis95 great.  I really hope that @Patowhiz can take over from here.  Maybe you can confirm?  

Then you can return to the various tasks on the 3-variable summarise.  Later that dialog will also call Patrick's Table Options sub-dialog, but not now!.

**Comment by Vitalis95** [comment]
@rdstern , @Patowhiz  can now take over the pull request .

**Comment by lilyclements** [comment]
> Then the formatting will be done on top of what the dialog produces once @lilyclements writes the necessary functions or writes to the gt team as Danny recommended.

@Patowhiz what needs to be written? My understanding was that the function to add / writing to the `gt` team was no longer needed since we found the function we wanted from `gt::tab_spanner_delim`.

**Comment by rdstern** [comment]
Yes @Vitalis95 and @lilyclements I thought the problems connecting this dialog to @Patowhiz sub-dialog were now over.  (That's after the discussions between Lily, David and Patrick in UK.)  But it seems not.
Vitalis, could you, maybe with help from @lilyclements, do the pivotting in the summary table, that you did in the frequency table (in the same dialog).  Then we'll get the initial gt summary table to approve and I trhen dream that we can at last hand over to @Patowhiz.  (Who I assume is hard at work adding nanoplots etc, so we have the full set of options from gt.

**Comment by rdstern** [comment]
@Vitalis95 and also a question for @lilyclements 

This is very promising.  As you say it just needs the numbering tidying up and it is ready to go.  

First my question - this applies to both the frequencies and the summaries.  Here are the frequencies:

image

And here is the result:

image

You see there is 1 column factor and it is the first in the list of 3 factors.  I suggest it should be the last one, so conceptually number 3 in the list, namely the fertgrp.

Similarly if there are 3 factors across we currently get this:

image

I suggest that's fine, but "the other order", so fertgroup at the top then village, then variety?  

That order will continue to the summaries, where the variables and summaries, by default (if left as 4 and 5) will become the columns.

@lilyclements as discussed, note also the need for the Drop Unused Levels to be added for both the frequency and the summary tables.  I hope that will not be too difficult.

**Comment by lilyclements** [comment]
@rdstern I don't have any strong opinions on if we should do the bottom-up or the top-down for counting the factors. However, I would have counted it as 1-2-3 from the top down. So that 1 was variety in the screenshot you've put in, in which case the order works as I would expect it to. But, I don't have any strong opinions so if you and @Vitalis95 agree it should be changed then that works!

> c) @lilyclements as discussed, note also the need for the Drop Unused Levels to be added for both the frequency and the summary tables. I hope that will not be too difficult.

Of course. @Vitalis95 can you add in a checkbox "Drop Unused Levels".
If this is checked, then `drop = TRUE`
If it is unchecked then `drop = FALSE`
Where `drop` is a parameter in our `data_book$summary_table` function

**Review by rdstern — COMMENTED** [review]
@Vitalis95 excellent, the frequency tables are now changed.  Keep up the good work.  I hope the addition of the Drop Unused Levels will also be easy.  It needs to go into both the frequency and the summary options

**Review by rdstern — CHANGES_REQUESTED** [review]
@Vitalis95 so far this is very promising!  I have started with the frequencies:  Survey data with Village and Variety.  (There are 10 non-zero combinations out of the 12).
a) Could you check the drop unused levels as the initial default.  (That's for consistency fith the Prepare > Data Reashape > Column Summaries dialog.
b) I think it is working perfectly for 1 or 2 column factors.  It gives a bug for zero.  I think you are still pivoting, and it isn;t needed then?

Still checking more

**Comment by lilyclements** [comment]
@Vitalis95 to point (c), add `names_sort = TRUE` as a parameter in `pivot_wider`. This will set the columns to not be by appearance (as it currently is)

**Review by rdstern — CHANGES_REQUESTED** [review]
@Vitalis95 excellent.  Three points, two of which are small and easy I hope.
a) The order of factor levels is now ok I think when you keep all levels, but not otherwise.  I think @lilyclements has mentioned that point.
b) The Variable and Summary up-downs I am happy are 0 when disabled, but, when enabled they ideally only go down to 1.  If you want them down to zero, treat 0 as one when you interpret.
c) The order in terms of rows and columns is almost correct.  I think it is correct for the columns, but not for the variables in the rows.  When they go down to 1 the variable should become the first rows, with the proper factors inside.  It never does this.

Note if c) is too tricky to fix completely, then I'll approve as it is and we can come back to it at peace later.

**Review by rdstern — COMMENTED** [review]
Happy the min is 1. But the max here should be 3 not 4.

image

I don't think anything else has changed yet.

**Comment by lilyclements** [comment]
@Vitalis95  what output would you expect in your example? We don't have anything for KESEN NEW in this one, so it starts with the first available level of KESEN (OLD)

**Review by rdstern — CHANGES_REQUESTED** [review]
a) @Vitalis95 I have just made an interesting discovery about the order of the variety factor levels.  They are still in observed order (rather than the defined order) when in the rows.  But there is an except -at least now.  If you don't drop unused levels (so you have the 12 leavels for Village & Variety together, then they are in the right order!

b) The up-down here still goes to 4, see below.  There are only 3 factors, so the default is correctly 3 and the limits should be 1 to 3, in this case:

image

c) Good news here.  I have added the multiple summaries.  Now the defaults are correct.  And the limits are correct!  Great!

image

e) Now the other way round - so multiple summaries and just one variable.  This is incorrect.  The variables is correctly disabled, but the summaries should be enabled.  It should be like just the Variables, see above.  So it should have a default of 3 and go from 1 up to 3 for this example.

image

I hope that's clear.  I'll wait and check the corresponding layouts later!

**Comment by rdstern** [comment]
@Vitalis95 This option - all 3 variables as columns - gave an error.  with the columns set to 2. 1, 0 it runs fine

image

Continuing checking

**Comment by rdstern** [comment]
@Vitalis95 I think your part is over now and we can pass it to @Patowhiz ?

He has demanded that it first works as earlier when we were using mmtable2.  I think it is better now, than before, but when I call his sub-dialog it gives this message.

image

I thought you were foing a pivot wider and then calling gt, but am I wrong?

**Comment by Vitalis95** [comment]
@rdstern,  Can this PR be merged then @Patowhiz can pick up from there?

**Comment by Vitalis95** [comment]
> @Vitalis95 I think your part is over now and we can pass it to @Patowhiz ?
> 
> He has demanded that it first works as earlier when we were using mmtable2. I think it is better now, than before.
> 
> But when I call his sub-dialog it gives this message.
> 
> image
> 
> It then goes into his sub-dialog as I expected. So I presume it is ready for @Patowhiz , but can you get rid of this message?

@rdstern  That message popping up  has been set in the sub-dialog

**Review by rdstern — APPROVED** [review]
@Patowhiz I am now approving.  @Vitalis95 has done a great job, and I think the only reason for not merging now is a message you have added, when your sub-dialog is called?  So can you check as well and then link in your stuff.

Thanks

**Comment by Patowhiz** [comment]
@rdstern I previously thought you wanted outputs similar to those of version 0.7.6. If the aim is to reproduce the outputs in 0.7.6 using `gt` R package then I think the scripts produced by this dialog are still no where near producing those outputs. @lilyclements may think otherwise and would be good to get her feedback. Below I give my analysis. 

**Current dialog inputs**
dialog

**Current output**
current_o

**0.7.6 dialog inputs**
status_076

**0.7.6 output (what I think is expected output, subject to @rdstern verification)**
output_076

**Code produced by 0.7.6 dialog. Notice how all the formatting is done at the dialog level, I think the sub-dialog was meant to add styling and other general formats in a basic way.**
```
summary_table <- data_book$summary_table(data_name="survey", columns_to_summarise=c("size","fert","yield"), factors=c("village","variety","fertgrp"), treat_columns_as_factor=FALSE, summaries=c("summary_mean"))

last_table <- (mmtable2::mmtable(data=summary_table, cells=value) + mmtable2::header_top_left(variable='summary-variable') + mmtable2::header_top_left(variable=village) + mmtable2::header_left_top(variable=variety) + mmtable2::header_left_top(variable=fertgrp))
data_book$add_table(table_name="last_table", table=last_table, data_name="survey")
data_book$get_tables(data_name="survey", table_name="last_table")
rm(list=c("last_table", "summary_table"
```

@lilyclements I tried adding the `dialog_df_tbl%>% gt::gt() %>% gt::tab_spanner_delim(delim = "_") ` as part of the script produced by this dialog but it doesn't produce the outputs that are similar to 0.7.6 or what I think @rdstern has in mind. My understanding is intermediary data frame produced is not in the shape that the `gt::tab_spanner_delim` could readily use, but I could be totally wrong.

**Code produced by current dialog**
```
summary_table <- data_book$summary_table(data_name="survey", columns_to_summarise=c("size","fert","yield"), factors=c("village","variety","fertgrp"), treat_columns_as_factor=FALSE, summaries=c("summary_mean"))
last_table <- (summary_table %>% pivot_wider(names_from=village, values_from=value) %>% gt::gt())
data_book$add_object(data_name="survey", object_name="last_table", object_type_label="table", object_format="html", object=last_table)
data_book$get_object_data(data_name="survey", object_name="last_table", as_file=TRUE)
rm(list=c("last_table", "summary_table"))
```

**Current dialog code modified**
```
summary_table <- data_book$summary_table(data_name="survey", columns_to_summarise=c("size","fert","yield"), factors=c("village","variety","fertgrp"), treat_columns_as_factor=FALSE, summaries=c("summary_mean"))
last_table <- (summary_table %>% pivot_wider(names_from=village, values_from=value) %>% gt::gt() %>% gt::tab_spanner_delim(delim = "_"))
data_book$add_object(data_name="survey", object_name="last_table", object_type_label="table", object_format="html", object=last_table)
data_book$get_object_data(data_name="survey", object_name="last_table", as_file=TRUE)
rm(list=c("last_table", "summary_table"))
```

**Comment by rdstern** [comment]
@Patowhiz you are right, we started with the 0.7.6 dialog:

image

Then we realised it wouldn't work properly for all the options needed.  So we hope the code you have is an improvement.

The main items not working were which positions the multiple variables or multiple summaries should take in the table.  This is vital and was not allowed for properly in the 0.7.6 dialog.

**Comment by lilyclements** [comment]
> I tried adding the dialog_df_tbl%>% gt::gt() %>% gt::tab_spanner_delim(delim = "_")  as part of the script produced by this dialog but it doesn't produce the outputs that are similar to 0.7.6 or what I think @rdstern has in mind.

@Patowhiz the reason is down to how many factors you've said you want to be in the rows and in the columns in both dialogs. **This comes down to how many variables are given in the `names_from` argument in `pivot_wider`**:

```
last_table <- (summary_table %>% pivot_wider(names_from=village, values_from=value) %>% gt::gt() %>% gt::tab_spanner_delim(delim = "_"))
```

* In 0.7.6 you have got your summaries and your village factor in the "pivot wider" part. I assume this is because you have not checked the "Display Summary_Variables as Rows", and you have set Column Factors to be 1 in the screenshot
* In your screenshot of the current dialog, we seem to just have the option to put in one factor as columns (pivot_wider). I thought we would have multiple here - like in this screenshot shared

image

**If you did summaries and village in the pivot wider:**

```
summary_table <- data_book$summary_table(data_name="survey", columns_to_summarise=c("size","fert","yield"), factors=c("village","variety","fertgrp"), treat_columns_as_factor=FALSE, summaries=c("summary_mean"))
last_table <- (summary_table %>% pivot_wider(names_from=c(village, `summary-variable`), values_from=value) %>% gt::gt() %>% gt::tab_spanner_delim(delim = "_"))
data_book$add_object(data_name="survey", object_name="last_table", object_type_label="table", object_format="html", object=last_table)
data_book$get_object_data(data_name="survey", object_name="last_table", as_file=TRUE)
rm(list=c("last_table", "summary_table"))
```

image

Also, really big thank you for sharing the code, and the screenshots of it all. That has really helped!

**Comment by Patowhiz** [comment]
Thanks @lilyclements and @rdstern for the feedback.

I spent sometime trying to get a sample R script that the current dialog should be producing to get the kind of outputs that 0.7.6 was producing. Below is a sample code what I came up with, which is consistent with the @lilyclements code suggestions. The key points being the current dialog controls need to be writing the necessary `gt` functions to get the desired outputs. Then the formatting sub-dialog will have to be strongly tied to the scripts that this kind of dialog produces (it currently can't serve all the needs of this dialog).

@rdstern you mention
> Then we realised it wouldn't work properly for all the options needed. So we hope the code you have is an improvement.
> 
> The main items not working were which positions the multiple variables or multiple summaries should take in the table. This is vital and was not allowed for properly in the 0.7.6 dialog.

Do we the options documented somewhere, in particular, mapping the controls functionalities to sample R code and it's corresponding outputs that you have in mind. I think that would be a good starting point before implementing this dialog.

```
summary_table <- data_book$summary_table(data_name="survey", columns_to_summarise=c("size","fert","yield"), factors=c("village","variety","fertgrp"), treat_columns_as_factor=FALSE, summaries=c("summary_mean"))

pivoted_table <- summary_table %>% tidyr::pivot_wider(names_from = c("village", "summary-variable"), values_from = value)

last_table <- pivoted_table %>% gt::gt(rowname_col="variety") %>% gt::sub_missing(missing_text = "") %>% gt::tab_spanner_delim(delim = "_") %>% gt::tab_row_group(label=".5-2cwt", rows=fertgrp==".5-2cwt", id=".5-2cwt")  %>% gt::tab_row_group(label=">2cwt", rows=fertgrp==">2cwt", id=">2cwt") %>% gt::tab_row_group(label="0cwt", rows=fertgrp=="0cwt", id="0cwt") %>% gt::cols_hide(columns = fertgrp)

data_book$add_object(data_name="survey", object_name="last_table", object_type_label="table", object_format="html", object=last_table)
data_book$get_object_data(data_name="survey", object_name="last_table", as_file=TRUE)

rm(list=c("last_table", "pivoted_table", "summary_table"))
```

**Comment by rdstern** [comment]
@lilyclements this is too advanced in R for me.  I hope you are able to repond?

**Comment by rdstern** [comment]
@lilyclements many thanks for the detailed reply.  @Patowhiz I hope that's what you needed to get something to merge?

**Comment by Patowhiz** [comment]
@lilyclements I'm using latest changes from the master and it could be @Vitalis95 is yet to add those options, I simply used what the dialog produces in this PR.

My aim of the sample code was to reproduce 0.7.6 output shown in my screenshot above based on the dialog inputs(to the options). It aims to demo the kind of gt code that will be needed for such output. I understand that the code produced by the dialog will vary depending on user inputs.

That's why I'm suggesting a 4 step process for this task.

1. Identifying required sample outputs.
2. Producing sample databook R scripts that produce the outputs.
3. Designing and implementing the dialog to produce the correct scripts and outputs, noting the design has already been done.
4. Evaluating how the tabulation object can be stored with metadata and how a subdialog can be built to read the metadata and allow users format the table according. 

As of now, comparing what 0.7.6 produces and this dialog, I don't see how we can do step 4 without doing step 3. However,  I do recognise that certain basic styling like Title, Footers and themes can be done with the current outputs. 

I stand to be corrected. 

@rdstern should we go ahead and link the current formatting subdialog noting, the current dialog's outputs is not what is expected and that work needs to be done to make it produce correct scripts and outputs  before step 4 can be done?

**Comment by lilyclements** [comment]
@Patowhiz can you either use the latest options from this PR, or can we discuss this in an issue if it's not related to this PR? Apologies for the confusion - I was assuming your suggestion was to be implemented in this PR.
We can create themes which do these sorts of things.

**Comment by rdstern** [comment]
@lilyclements and @Patowhiz I remain nomplussed by the discussion.
But I report with relief that we are all (I assume) discussing the latest version, where @Vitalis95 did a great job last week, which I thought was what Patrick needed to get started.  Here is an example of his completed dialog:

image

Whe you see the important addition of the Drop unused levels is included.

Here is the resulting table:

image

Note the additional title, i.e. it already works with Patrick's sub-dialog.  I was under the impression that this was what he was demanding, before he started

I have assuming @Patowhiz starting point is therefore to check that the code is solid, and then merge.  I approved last week. 

Then the remaining work is just to include the extra tabs that are now possible with the latest R?

I note we have our regular meeting with @ChrisMarsh82 today.  I cannot be there, because of e-SIAC but I hope @Patowhiz can contine with the meeting to report progress - or otherwise?

**Review by Patowhiz — APPROVED** [review]

**Pull request merged**
