### PR TITLE
Adding help id's

### PR DESCRIPTION
**Pull request by Fidel365**
Fixes partially issue #8786.
@rdstern, some of the help id's you have provided are not working; that is for part (b), (c), (d) , the id's provided are not working but if itry to use different valid id's , they work just fine. Otherwise, the remaining part of the issue is ready for review

### CODE REVIEW

**Comment by rdstern** [comment]
@Fidel365 it is understandable that some of the new IDs don't yet work.  They need the new help file first.

**Comment by rdstern** [comment]
@Fidel365 I just checked #8786 so the help 4 issue.  I assume you did not change anything from 1, 2, and 3, yet.  Tell me when you do.
I checked the results and just found 2 that don't work.
In point i, the sub-dialog help doesn't work yet.  It should have help ID of 268.
And o went to the wrong place.  That may be my mistake, but could you check you put ID of 490 there.

Thanks so far.

**Comment by rdstern** [comment]
@Fidel365 you have gone quiet again?  I assumed the updates for the 4 issues would be about one day of work together.  I wonder what has happened?  Could you please keep @N-thony updated when there are days when you are not abler to work?

**Comment by Fidel365** [comment]
Pr #8799 fixes the issue

**Pull request closed without merging**
