### PR TITLE
Fixing the displaying roman in the grid

### LINKED ISSUE #9005: REturning presentation of roman to the calculator
@Fidel365 I think - except for presenting Roman numerals in the reogrid (that may need discussion with @N-thony) that the improvements to the calculator (again except for the great addition to scalars by Antoine) are now done.

There are 9 open issues that relate to the calculator, namely
#8940 
#8931 
#8925 
#8918 
#8905 
#8904 
#8902 
#8884 
#8820 

I think they may all be done and hence could be closed.  Could you please check, report and close - or get @N-thony to close if you are not sure.

Thanks

Roger

### PR DESCRIPTION
**Pull request by N-thony**
Fixes #9005 
@rdstern @Fidel365 I have fixed the displaying of roman in the grid. Have a look.

### CODE REVIEW

**Comment by rdstern** [comment]
@N-thony I was excited, so tried straight away:

image

Still seems as before though.  In the reogrid it still looks as before and is not indicated as (R) or (S)?  It looks roman in the R viewer.

**Comment by Vitalis95** [comment]
@N-thony @rdstern , I made a new data frame ,  used the calculator roman key and it works fine. It also works well with any loaded data frame

**Comment by rdstern** [comment]
@jkmusyoka please can you try this as well.  
@Patowhiz please can you try too.  

@N-thony in your fix to this issue can you please add the column type as (R) or (S) to the roman variable.


I chec ked afain on my Dell machine and also confirm that (for me) the output window shows the Roman, the information metadata shows it is roman, it displays as roman in the R viewer.  It just doesn't display as roman in reogrid.

**Review by Patowhiz — APPROVED** [review]

**Review by rdstern — APPROVED** [review]
@Patowhiz I am approving. 
I assume ths means that @Fidel365 pull request can also be closed?

**Pull request merged**
